### ISSUE TITLE
SX-Aurora TSUBASA Vector Engine

### ISSUE THREAD

**Issue by sanxiyn** [cpredef/predef#19]
See its [homepage](https://sx-aurora.github.io/) and LLVM support is [upstream](https://github.com/llvm/llvm-project/tree/main/llvm/lib/Target/VE). The architecture documentation is at https://sxauroratsubasa.sakura.ne.jp/Documentation. Predefined macros are defined in "C/C++ Compiler User's Guide" section 9.2.4 "Predefined Macro". The architecture is identified by `__ve__`.

**Comment by a1batross** [comment]
Thanks for contribution!

Do you by chance have access to NEC C/C++ Compiler? Is it uses EDG frontend, or it's custom build of Clang/LLVM? I would like to add that too.

**Comment by a1batross** [comment]
Closed by https://github.com/cpredef/predef/commit/d48b93cd5c92ef64dc098a7cf9ba3f3adf3ad870
