### ISSUE TITLE
Describe LoongArch macros

### ISSUE THREAD

**Issue by a1batross** [cpredef/predef#6]
There is an ongoing discussion about predefined macros happening on their GitHub: https://github.com/loongson/LoongArch-Documentation/pull/28

GCC and LLVM recently added support for this architecture. But I think, it should be added after the changes will be merged.

cc @xen0n

**Comment by sanxiyn** [comment]
Update: PR is merged and updated documentation is available at https://loongson.github.io/LoongArch-Documentation/LoongArch-toolchain-conventions-EN.html.
