### ISSUE TITLE
Redirect to here from sourceforge?

### ISSUE THREAD

**Issue by bagder** [cpredef/predef#8]
Since the old location at https://sourceforge.net/p/predef/wiki/Home/ is such an old established place for this data, I assume lots of people will still end up there without realizing we've moved over and update the information here now.

Bjorn, can you maybe add a redirect or at least a prominent note on that page that the information is now here?

**Comment by breese** [comment]
Will do.

We should also change the contribution information from the mailing-list to GitHub issues.

**Comment by breese** [comment]
SourceForge has an option to redirect a project, but it just adds a button under the title saying "_This project can now be found here_".

I have not found an option to automatically redirect the wiki or predef.sourceforge.net to here. If anybody knows how, please tell.

**Comment by breese** [comment]
predef.sourceforge.net now automatically redirects here.

**Comment by a1batross** [comment]
It's giving 403 for me, but I'm connected through VPN, my IP may be just blocked.

**Comment by bagder** [comment]
I got a 403 at first too a few hours ago, but now it works fine for me

**Comment by a1batross** [comment]
Yep, works!
